### PR TITLE
Added new post-47 to OL track - virtualization - Build Custom Images with Podman

### PR DESCRIPTION
**Pull request by mlittlec**
Add new Clip to the Linux/Podman track on  OLTrain:

- _Build Custom Images_

### CODE REVIEW

**Review by bgraef — COMMENTED** [review]
Need to remove the `with Podman` from the title of the post

**Review by mlittlec — COMMENTED** [review]
Title updated as requested 👍

**Review by bgraef — COMMENTED** [review]
Looks good 👍

**Review by bgraef — APPROVED** [review]
Looks good 👍

**Pull request merged**
